Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,7 +7,11 @@ executors:
 
 parameters:
   ENVIRONMENT:
-    description: "Specifies the deployment environment: dev, stage, or prod."
+    description: "Specifies the deployment environment for the application, in lowercase. This variable determines whether the build and deployment process is executed in the development (dev), staging (stage), or production (prod) environment."
+    type: string
+    default: ""
+  TAG_ID:
+    description: "Tag for the Docker image. Shortened commit SHA."
     type: string
     default: ""
 
@@ -25,17 +29,18 @@ jobs:
       - run:
           name: Extract and Print ENVIRONMENT value
           command: |
-            echo "Extracted ENVIRONMENT value: << parameters.ENVIRONMENT >>"
-            echo "export ENVIRONMENT=<< parameters.ENVIRONMENT >>" >> $BASH_ENV
+            ENVIRONMENT="<< parameters.ENVIRONMENT >>"
+            echo "Extracted ENVIRONMENT value: $ENVIRONMENT"
+            echo "export ENVIRONMENT=$ENVIRONMENT" >> $BASH_ENV
       - checkout
       - run:
           name: Authenticate with GCP
           command: |
             echo "$GCLOUD_SERVICE_KEY" > ./service-account.json
-            SERVICE_PROJECT_ID="${Name_Prefix}<< parameters.ENVIRONMENT >>"
+            SERVICE_PROJECT_ID="${Name_Prefix}${ENVIRONMENT}"
             echo 'export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json' >> $BASH_ENV
             gcloud auth activate-service-account --key-file=./service-account.json
-            gcloud --quiet config set project "$SERVICE_PROJECT_ID"
+            gcloud --quiet config set project "${Name_Prefix}${ENVIRONMENT}"
       - run:
           name: Set Short Commit SHA
           command: |
@@ -46,11 +51,21 @@ jobs:
       - run:
           name: Building & Pushing Docker Image
           command: |
-            gcloud secrets versions access latest --project="${Name_Prefix}<< parameters.ENVIRONMENT >>" --secret="${Name_Prefix}<< parameters.ENVIRONMENT >>-python-service" >> .env
-            rm -f ./service-account.json
-            docker build --platform=linux/amd64 --pull -t "$GCP_REGION-docker.pkg.dev/${Name_Prefix}<< parameters.ENVIRONMENT >>/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID" -f Dockerfile .
+            if [[ -z "$TAG_ID" ]]; then
+              echo "Error: TAG_ID is not set!"
+              exit 1
+            fi
+            if [[ -f ".env" ]]; then
+              echo ".env file found. Deleting it..."
+              rm -rf .env
+            else
+              echo ".env file not found. Skipping deletion."
+            fi
+            gcloud secrets versions access latest --project="${Name_Prefix}${ENVIRONMENT}" --secret="${Name_Prefix}${ENVIRONMENT}-python-service" >> .env
+            rm -rf ./service-account.json
+            docker build --platform=linux/amd64 --pull -t "$GCP_REGION-docker.pkg.dev/${Name_Prefix}${ENVIRONMENT}/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID" -f Dockerfile .
             gcloud auth configure-docker "$GCP_REGION-docker.pkg.dev" --quiet > /dev/null 2>&1
-            docker push "$GCP_REGION-docker.pkg.dev/${Name_Prefix}<< parameters.ENVIRONMENT >>/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID"
+            docker push "$GCP_REGION-docker.pkg.dev/${Name_Prefix}${ENVIRONMENT}/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID"
       - persist_to_workspace:
           root: /tmp
           paths:
@@ -66,8 +81,9 @@ jobs:
       - run:
           name: Extract and Print ENVIRONMENT value
           command: |
-            echo "Extracted ENVIRONMENT value: << parameters.ENVIRONMENT >>"
-            echo "export ENVIRONMENT=<< parameters.ENVIRONMENT >>" >> $BASH_ENV
+            ENVIRONMENT="<< parameters.ENVIRONMENT >>"
+            echo "Extracted ENVIRONMENT value: $ENVIRONMENT"
+            echo "export ENVIRONMENT=$ENVIRONMENT" >> $BASH_ENV
       - attach_workspace:
           at: /tmp
       - checkout
@@ -75,20 +91,27 @@ jobs:
           name: Authenticate with GCP
           command: |
             echo "$GCLOUD_SERVICE_KEY" > ./service-account.json
-            SERVICE_PROJECT_ID="${Name_Prefix}<< parameters.ENVIRONMENT >>"
+            SERVICE_PROJECT_ID="${Name_Prefix}${ENVIRONMENT}"
             echo 'export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json' >> $BASH_ENV
             gcloud auth activate-service-account --key-file=./service-account.json
-            gcloud --quiet config set project "$SERVICE_PROJECT_ID"
+            gcloud --quiet config set project "${Name_Prefix}${ENVIRONMENT}"
       - run:
           name: Fetch TAG_ID
           command: |
-            export TAG_ID=$(cat /tmp/TAG_ID.txt)
-            echo "Using TAG_ID: $TAG_ID"
+            TAG_ID=$(cat /tmp/TAG_ID.txt)
+            export TAG_ID=${TAG_ID}
             echo "export TAG_ID=${TAG_ID}" >> $BASH_ENV
       - run:
           name: Deploying the Application
           command: |
-            bash .circleci/deploy.sh $TAG_ID
+            ENVIRONMENT="<< parameters.ENVIRONMENT >>"
+            echo "Extracted ENVIRONMENT value: $ENVIRONMENT"
+            echo "export ENVIRONMENT=$ENVIRONMENT" >> $BASH_ENV
+            export Name_Prefix=$Name_Prefix
+            export ENVIRONMENT=$ENVIRONMENT
+            echo "Deploying application with ENVIRONMENT: $ENVIRONMENT"
+            bash .circleci/deploy.sh ${TAG_ID}
+
 workflows:
   Moneta-PYTHON-SERVICE-PROD:
     when:
@@ -102,11 +125,9 @@ workflows:
           filters:
             branches:
               only: main
-
       - Hold_for_approval:
           requires:
             - Building_App
-
       - Deploying_App:
           ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
           requires:
@@ -128,7 +149,6 @@ workflows:
           filters:
             branches:
               only: main
-
       - Deploying_App:
           ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
           requires:
