Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,60 +3,72 @@ version: 2.1
 executors:
   moneta-runner-executor:
     machine: true
-    resource_class: moneta-labs/moneta-runner
+    resource_class: moneta-labs/moneta-runner   
 
 parameters:
-  run_manually:
+  manual_trigger:
+    description: "Controls whether the pipeline requires manual triggering (true) or runs automatically (false)."
     type: boolean
     default: false
   ENVIRONMENT:
+    description: "Specifies the deployment environment for the application, in lowercase. This variable determines whether the build and deployment process is executed in the development (dev), staging (stage), or production (prod) environment."
     type: string
     default: ""
   TAG_ID:
+    description: "Tag for the Docker image. Shortened commit SHA."
     type: string
     default: ""
 
 jobs:
   Hold_for_approval:
-    type: approval
-
+    type: approval  
   Building_App:
     machine: true
     resource_class: moneta-labs/moneta-runner
     parameters:
       ENVIRONMENT:
         type: string
-      run_manually:
-        type: boolean
     steps:
       - run:
-          name: Check run_manually flag
+          name: Extract and Print ENVIRONMENT value
           command: |
-            if [ "<< parameters.run_manually >>" != "true" ]; then
-              echo "Skipping Building_App as run_manually is false"
-              circleci step halt
-            fi
+            ENVIRONMENT="<< parameters.ENVIRONMENT >>"
+            echo "Extracted ENVIRONMENT value: $ENVIRONMENT"
+            echo "export ENVIRONMENT=$ENVIRONMENT" >> $BASH_ENV
       - checkout
       - run:
           name: Authenticate with GCP
           command: |
             echo "$GCLOUD_SERVICE_KEY" > ./service-account.json
+            SERVICE_PROJECT_ID="${Name_Prefix}${ENVIRONMENT}"
             echo 'export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json' >> $BASH_ENV
             gcloud auth activate-service-account --key-file=./service-account.json
-            gcloud --quiet config set project "${Name_Prefix}<< parameters.ENVIRONMENT >>"
+            gcloud --quiet config set project "${Name_Prefix}${ENVIRONMENT}"
       - run:
-          name: Set TAG_ID
+          name: Set Short Commit SHA
           command: |
             export TAG_ID=${CIRCLE_SHA1:0:8}
             echo "export TAG_ID=${TAG_ID}" >> $BASH_ENV
+            echo "Generated TAG_ID: $TAG_ID"
             echo $TAG_ID > /tmp/TAG_ID.txt
       - run:
-          name: Build and Push Docker Image
+          name: Building & Pushing Docker Image
           command: |
-            gcloud secrets versions access latest --project="${Name_Prefix}<< parameters.ENVIRONMENT >>" --secret="${Name_Prefix}<< parameters.ENVIRONMENT >>-python-service" >> .env
-            docker build --platform=linux/amd64 -t "$GCP_REGION-docker.pkg.dev/${Name_Prefix}<< parameters.ENVIRONMENT >>/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID" -f Dockerfile .
-            gcloud auth configure-docker "$GCP_REGION-docker.pkg.dev" --quiet
-            docker push "$GCP_REGION-docker.pkg.dev/${Name_Prefix}<< parameters.ENVIRONMENT >>/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID"
+            if [[ -z "$TAG_ID" ]]; then
+              echo "Error: TAG_ID is not set!"
+              exit 1
+            fi
+            if [[ -f ".env" ]]; then
+              echo ".env file found. Deleting it..."
+              rm -rf .env
+            else
+              echo ".env file not found. Skipping deletion."
+            fi
+            gcloud secrets versions access latest --project="${Name_Prefix}${ENVIRONMENT}" --secret="${Name_Prefix}${ENVIRONMENT}-python-service" >> .env
+            rm -rf ./service-account.json
+            docker build --platform=linux/amd64 --pull -t "$GCP_REGION-docker.pkg.dev/${Name_Prefix}${ENVIRONMENT}/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID" -f Dockerfile .
+            gcloud auth configure-docker "$GCP_REGION-docker.pkg.dev" --quiet > /dev/null 2>&1
+            docker push "$GCP_REGION-docker.pkg.dev/${Name_Prefix}${ENVIRONMENT}/${Name_Prefix}-python-service/${Name_Prefix}-python-service:$TAG_ID"
       - persist_to_workspace:
           root: /tmp
           paths:
@@ -68,16 +80,13 @@ jobs:
     parameters:
       ENVIRONMENT:
         type: string
-      run_manually:
-        type: boolean
     steps:
       - run:
-          name: Check run_manually flag
+          name: Extract and Print ENVIRONMENT value
           command: |
-            if [ "<< parameters.run_manually >>" != "true" ]; then
-              echo "Skipping Deploying_App as run_manually is false"
-              circleci step halt
-            fi
+            ENVIRONMENT="<< parameters.ENVIRONMENT >>"
+            echo "Extracted ENVIRONMENT value: $ENVIRONMENT"
+            echo "export ENVIRONMENT=$ENVIRONMENT" >> $BASH_ENV
       - attach_workspace:
           at: /tmp
       - checkout
@@ -85,40 +94,50 @@ jobs:
           name: Authenticate with GCP
           command: |
             echo "$GCLOUD_SERVICE_KEY" > ./service-account.json
+            SERVICE_PROJECT_ID="${Name_Prefix}${ENVIRONMENT}"
             echo 'export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json' >> $BASH_ENV
             gcloud auth activate-service-account --key-file=./service-account.json
-            gcloud --quiet config set project "${Name_Prefix}<< parameters.ENVIRONMENT >>"
+            gcloud --quiet config set project "${Name_Prefix}${ENVIRONMENT}"
       - run:
-          name: Deploy the App
+          name: Fetch TAG_ID
           command: |
             TAG_ID=$(cat /tmp/TAG_ID.txt)
-            echo "Using TAG_ID: $TAG_ID"
-            bash .circleci/deploy.sh $TAG_ID
+            export TAG_ID=${TAG_ID}
+            echo "export TAG_ID=${TAG_ID}" >> $BASH_ENV
+      - run:
+          name: Deploying the Application
+          command: |
+            ENVIRONMENT="<< parameters.ENVIRONMENT >>"
+            echo "Extracted ENVIRONMENT value: $ENVIRONMENT"
+            echo "export ENVIRONMENT=$ENVIRONMENT" >> $BASH_ENV
+            export Name_Prefix=$Name_Prefix
+            export ENVIRONMENT=$ENVIRONMENT
+            echo "Deploying application with ENVIRONMENT: $ENVIRONMENT"
+            bash .circleci/deploy.sh ${TAG_ID}
 
 workflows:
   Moneta-PYTHON-SERVICE:
-    when: << pipeline.parameters.run_manually >>
+    when: << pipeline.parameters.manual_trigger >>
     jobs:
       - Building_App:
           ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
-          run_manually: << pipeline.parameters.run_manually >>
           filters:
             branches:
               only: main
-
       - Hold_for_approval:
+          type: approval
           requires:
             - Building_App
           filters:
             branches:
               only: main
-
+          when:
+            condition:
+              equal: ["prod", << pipeline.parameters.ENVIRONMENT >>]
       - Deploying_App:
           requires:
             - Hold_for_approval
           ENVIRONMENT: << pipeline.parameters.ENVIRONMENT >>
-          run_manually: << pipeline.parameters.run_manually >>
           filters:
             branches:
               only: main
-
